In [42]:
# Random Forest Classifier

# Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [43]:
# Importing the datasets

dataset = pd.read_csv("data_for_labeling.csv")
X = dataset.iloc[:, :-1]
Y = dataset.iloc[:,-1]

#data to be split into X features set and Y label set 

In [44]:
dataset

0  1  2  3  4  5  6  7  8  9  ...  5/1/2019  6/1/2017  6/1/2019  \
0      0  0  0  0  0  0  0  0  0  0  ...         0        11        11   
1      0  0  0  0  0  0  0  0  0  0  ...         0         2         0   
2      0  0  0  0  0  0  0  0  0  0  ...         0       136       136   
3      0  0  0  0  0  0  0  0  0  0  ...         0         1         1   
4      0  0  0  0  0  0  0  0  0  0  ...       138         0         6   
5      0  0  0  0  0  0  0  0  0  0  ...         0         2         2   
6      0  0  0  0  0  0  0  0  0  0  ...        10         3        17   
7      0  0  0  0  0  0  0  0  0  0  ...         0         1         1   
8      0  0  0  0  0  0  0  0  0  0  ...         6         3         0   
9      0  0  0  0  0  0  0  0  0  0  ...         0         4         0   
10     0  0  0  0  0  0  0  0  0  0  ...         1         7         0   
11     0  0  0  0  0  0  0  0  0  0  ...        71        50        79   
12     0  0  0  0  0  0  0  0  0  0  ...         0        24        24   
13     0  0  0  0  0  0  0  0  0  0  ...         9        30        15   
14     1  0  0  0  0  0  0  0  0  0  ...         0         2         2   
15     1  0  0  0  0  0  0  0  0  0  ...         1         1         1   
16     1  0  0  0  0  0  0  0  0  0  ...         2         2         2   
17     1  0  0  0  0  0  0  0  0  0  ...         1         1         1   
18     1  0  0  0  0  0  0  0  0  0  ...         1         1         0   
19     1  0  0  0  0  0  0  0  0  0  ...         0         1         0   
20     1  0  0  0  0  0  0  0  0  0  ...         0         0         0   
21     1  0  0  0  0  0  0  0  0  0  ...         2         3         2   
22     1  0  0  0  0  0  0  0  0  0  ...         1         1         1   
23     1  0  0  0  0  0  0  0  0  0  ...         2         2         1   
24     1  0  0  0  0  0  0  0  0  0  ...         1         1         1   
25     1  0  0  0  0  0  0  0  0  0  ...         6         6         6   
26     1  0  0  0  0  0  0  0  0  0  ...         1         1         1   
27     1  0  0  0  0  0  0  0  0  0  ...         1         1         1   
28     1  0  0  0  0  0  0  0  0  0  ...         1         0         0   
29     1  0  0  0  0  0  0  0  0  0  ...         3         2         2   
...   .. .. .. .. .. .. .. .. .. ..  ...       ...       ...       ...   
28330  0  0  0  0  0  0  0  0  0  0  ...        56        56        56   
28331  0  0  0  0  0  0  0  0  0  0  ...       614       614       614   
28332  0  0  0  0  0  0  0  0  0  0  ...        29        29        29   
28333  0  0  0  0  0  0  0  0  0  0  ...        41        41        41   
28334  0  0  0  0  0  0  0  0  0  0  ...       120       120       120   
28335  0  0  0  0  0  0  0  0  0  0  ...       190       190       190   
28336  0  0  0  0  0  0  0  0  0  0  ...         9         9         9   
28337  0  0  0  0  0  0  0  0  0  0  ...       710       710       710   
28338  0  0  0  0  0  0  0  0  0  0  ...         0        69        69   
28339  0  0  0  0  0  0  0  0  0  0  ...        50        50        50   
28340  0  0  0  0  0  0  0  0  0  0  ...        30        30        30   
28341  0  0  0  0  0  0  0  0  0  0  ...       358       358       358   
28342  0  0  0  0  0  0  0  0  0  0  ...       139       139       139   
28343  0  0  0  0  0  0  0  0  0  0  ...        51        51        51   
28344  0  0  0  0  0  0  0  0  0  0  ...       210       210       210   
28345  0  0  0  0  0  0  0  0  0  0  ...        87        87        87   
28346  0  0  0  0  0  0  0  0  0  0  ...         5         5         5   
28347  0  0  0  0  0  0  0  0  0  0  ...       297       297       297   
28348  0  0  0  0  0  0  0  0  0  0  ...      1021      1021      1021   
28349  0  0  0  0  0  0  0  0  0  0  ...       143       143       143   
28350  0  0  0  0  0  0  0  0  0  0  ...         4         4         4   
28351  0  0  0  0  0  0  0  0  0  0  ...        78        78        78   
28352  0  0

In [45]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.4, random_state = 0)


In [46]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_Train = sc_X.fit_transform(X_Train)
X_Test = sc_X.transform(X_Test)

/home/micnice/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/home/micnice/anaconda3/lib/python3.7/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
/home/micnice/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  


In [47]:
# Fitting the classifier into the Training set

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 200, criterion = 'entropy', random_state = 0)
classifier.fit(X_Train,Y_Train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [48]:
# Predicting the test set results

Y_Pred = classifier.predict(X_Test)

In [49]:
# Making the Confusion Matrix 

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_Test, Y_Pred)

In [50]:
#Visualizations
cm

array([[18714,    74,     8],
       [   83,  1994,    36],
       [   13,    72,   276]])

In [53]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(Y_Test, Y_Pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_Test, Y_Pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_Test, Y_Pred)))

Mean Absolute Error: 0.014433474377056887
Mean Squared Error: 0.016408086506817115
Root Mean Squared Error: 0.1280940533624302


In [55]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(Y_Test,Y_Pred))
print(classification_report(Y_Test,Y_Pred))
print(accuracy_score(Y_Test, Y_Pred))

[[18714    74     8]
 [   83  1994    36]
 [   13    72   276]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00     18796
           1       0.93      0.94      0.94      2113
           2       0.86      0.76      0.81       361

   micro avg       0.99      0.99      0.99     21270
   macro avg       0.93      0.90      0.91     21270
weighted avg       0.99      0.99      0.99     21270

0.9865538316878232
